referencePatternsFileNamesList = ['AcetaldehydeNISTRefMixed2_unused_iter_6.csv']
referencePatternsFormsList = ['xyyy']
dataToAnalyzeFileName = '2-CrotAcetExp#2Truncated_remaining_iter_6.csv'
referencePatternTimeRanges = []
ionizationDataFileName = '_ProvidedIonizationData.csv'
iterativeAnalysis = True
iterationNumber = 6
iterationSuffix = '_iter_6'
unusedMolecules = ['CO', 'CO2', 'H2']
oldReferenceFileName = ['AcetaldehydeNISTRefMixed2_unused_iter_5.csv']
oldDataToAnalyzeFileName = '2-CrotAcetExp#2Truncated_remaining_iter_5.csv'
nextRefFileName = ['AcetaldehydeNISTRefMixed2_unused_iter_6.csv']
nextExpFileName = '2-CrotAcetExp#2Truncated_remaining_iter_6.csv'
preProcessing = 'yes'
dataAnalysis = 'yes'
dataSimulation = 'yes'
grapher = 'no'
stopAtGraphs = True
timeRangeLimit = 'yes'
timeRangeStart = 176.0
timeRangeFinish = 200.0
specificMolecules = 'yes'
chosenMoleculesNames = ['CO', 'CO2', 'H2']
specificMassFragments = 'yes'
chosenMassFragments = [2, 18, 26, 27, 28, 29, 31, 39, 41, 44, 45, 56, 57, 70]
moleculeLikelihoods = []
sensitivityValues = []
linearBaselineCorrectionSemiAutomatic = 'no'
baselineType = ['linear']
massesToBackgroundCorrect = [2, 18, 27, 28, 31, 39, 41, 44, 57, 70]
earlyBaselineTimes = [[177.0, 177.1]]
lateBaselineTimes = [[901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [901.0, 902.0], [901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [901.0, 902.0]]
backgroundMassFragment = []
backgroundSlopes = []
backgroundIntercepts = []
interpolateYorN = 'no'
marginalChangeRestriction = 2.0
ignorableDeltaYThreshold = 0.01
dataLowerBound = []
dataUpperBound = []
dataRangeSpecifierYorN = 'no'
signalOrConcentrationRange = 'signal'
csvFile = 'yes'
moleculesToRestrict = []
csvFileName = 'rangestemplate.csv'
bruteIncrements = []
permutationNum = 1000
maxPermutations = 100001
scaleRawDataOption = 'manual'
scaleRawDataFactor = 1.0
tuningCorrection = 'no'
tuningCorrectPatternInternalVsExternal = 'External'
referenceFileStandardTuningAndForm = []
createMixedTuningPattern = False
referenceFileExistingTuningAndForm = 'AcetaldehydeMeasuredRef.csv'
referenceFileDesiredTuningAndForm = 'AcetaldehydeOnlyNISTRef.csv'
referenceCorrectionCoefficients = {'A': 0.0, 'B': 0.0, 'C': 1.0}
referenceCorrectionCoefficients_cov = [0, 0, 0]
extractReferencePatternFromDataOption = 'no'
rpcMoleculesToChange = ['Crotyl Alcohol']
rpcMoleculesToChangeMF = [[70, 57]]
rpcTimeRanges = [[300, 500]]
applyReferenceMassFragmentsThresholds = 'no'
referenceMassFragmentFilterThreshold = [6.0]
referenceSignificantFragmentThresholds = [6.0]
lowerBoundThresholdChooser = 'no'
massesToLowerBoundThresholdFilter = []
lowerBoundThresholdPercentage = [0.25]
lowerBoundThresholdAbsolute = []
dataSmootherYorN = 'no'
dataSmootherChoice = 'timerange'
dataSmootherTimeRadius = 7
dataSmootherPointRadius = 5
dataSmootherHeadersToConfineTo = []
polynomialOrder = 1
applyRawSignalThresholds = 'no'
rawSignalThresholdValue = [1e-07]
sensitivityThresholdValue = [1]
rawSignalThresholdDivider = []
rawSignalThresholdLimit = 'no'
rawSignalThresholdLimitPercent = []
negativeAnalyzerYorN = 'no'
NegativeAnalyzerTopNContributors = 5
NegativeAnalyzerBaseNumberOfGridIntervals = 5
calculateUncertaintiesInConcentrations = False
referenceFileUncertainties = 2
collectedFileUncertainties = 'Auto'
referenceCorrectionCoefficientsUncertainties = None
referenceCorrectionCoefficientsIonizationUncertainties = None
solverChoice = 'sls'
uniqueOrCommon = 'common'
slsWeighting = [1, 0, 0, 0]
slsFinish = 'brute'
slsUniquePositiveConcentrationsOnly = False
objectiveFunctionType = 'ssr'
distinguished = 'yes'
fullBrute = 'yes'
SLSUniqueExport = 'yes'
implicitSLScorrection = False
implicitSLSRecursion = 0
finalOptimization = 'None'
concentrationFinder = 'yes'
moleculesTSC_List = ['Acetaldehyde', 'CO', 'Ethanol']
TSC_List_Type = 'SeparateMolecularFactors'
moleculeSignalTSC_List = [1.66945, 1.2, 1.1]
massNumberTSC_List = [29, 28, 44]
moleculeConcentrationTSC_List = [0.05, 0.01, 0.03]
unitsTSC = 'bar'
preProcessedDataOutputName = 'PreProcessedData.csv'
resolvedScaledConcentrationsOutputName = 'ScaledConcentrations.csv'
scaledConcentrationsPercentages = 'ScaledConcentrationPercentages.csv'
concentrationsOutputName = 'ResolvedConcentrations.csv'
simulatedSignalsOutputName = 'SimulatedRawSignals.csv'
TotalConcentrationsOutputName = 'TotalConcentrations.csv'
ExportAtEachStep = 'yes'
generatePercentages = 'no'
checkpoint = 10.9659829
start = 10.5760131
timeSinceLastCheckpoint = 0.2958154999999998
iterationNumber = 6

__var_list__ = ['referencePatternsFileNamesList','referencePatternsFormsList','dataToAnalyzeFileName','referencePatternTimeRanges','ionizationDataFileName','iterativeAnalysis','iterationNumber','iterationSuffix','unusedMolecules','oldReferenceFileName','oldDataToAnalyzeFileName','nextRefFileName','nextExpFileName','preProcessing','dataAnalysis','dataSimulation','grapher','stopAtGraphs','timeRangeLimit','timeRangeStart','timeRangeFinish','specificMolecules','chosenMoleculesNames','specificMassFragments','chosenMassFragments','moleculeLikelihoods','sensitivityValues','linearBaselineCorrectionSemiAutomatic','baselineType','massesToBackgroundCorrect','earlyBaselineTimes','lateBaselineTimes','backgroundMassFragment','backgroundSlopes','backgroundIntercepts','interpolateYorN','marginalChangeRestriction','ignorableDeltaYThreshold','dataLowerBound','dataUpperBound','dataRangeSpecifierYorN','signalOrConcentrationRange','csvFile','moleculesToRestrict','csvFileName','bruteIncrements','permutationNum','maxPermutations','scaleRawDataOption','scaleRawDataFactor','tuningCorrection','tuningCorrectPatternInternalVsExternal','referenceFileStandardTuningAndForm','createMixedTuningPattern','referenceFileExistingTuningAndForm','referenceFileDesiredTuningAndForm','referenceCorrectionCoefficients','referenceCorrectionCoefficients_cov','extractReferencePatternFromDataOption','rpcMoleculesToChange','rpcMoleculesToChangeMF','rpcTimeRanges','applyReferenceMassFragmentsThresholds','referenceMassFragmentFilterThreshold','referenceSignificantFragmentThresholds','lowerBoundThresholdChooser','massesToLowerBoundThresholdFilter','lowerBoundThresholdPercentage','lowerBoundThresholdAbsolute','dataSmootherYorN','dataSmootherChoice','dataSmootherTimeRadius','dataSmootherPointRadius','dataSmootherHeadersToConfineTo','polynomialOrder','applyRawSignalThresholds','rawSignalThresholdValue','sensitivityThresholdValue','rawSignalThresholdDivider','rawSignalThresholdLimit','rawSignalThresholdLimitPercent','negativeAnalyzerYorN','NegativeAnalyzerTopNContributors','NegativeAnalyzerBaseNumberOfGridIntervals','calculateUncertaintiesInConcentrations','referenceFileUncertainties','collectedFileUncertainties','referenceCorrectionCoefficientsUncertainties','referenceCorrectionCoefficientsIonizationUncertainties','solverChoice','uniqueOrCommon','slsWeighting','slsFinish','slsUniquePositiveConcentrationsOnly','objectiveFunctionType','distinguished','fullBrute','SLSUniqueExport','implicitSLScorrection','implicitSLSRecursion','finalOptimization','concentrationFinder','moleculesTSC_List','TSC_List_Type','moleculeSignalTSC_List','massNumberTSC_List','moleculeConcentrationTSC_List','unitsTSC','preProcessedDataOutputName','resolvedScaledConcentrationsOutputName','scaledConcentrationsPercentages','concentrationsOutputName','simulatedSignalsOutputName','TotalConcentrationsOutputName','ExportAtEachStep','generatePercentages','checkpoint','start','timeSinceLastCheckpoint','iterationNumber']
chosenMoleculesNames = ['CO', 'CO2', 'H2']
chosenMassFragments = [2, 28, 44]
